name: github pages deploy

on:
  push:
    branches:
      - main

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: install
        run: gem install bundler && bundle
      - name: test
        run: bundle exec rake test
      - name: build
        run: bundle exec rake reset && bundle exec rake build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
